const GET_PAGE_LIST = 'GET_PAGE_LIST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const POST_USER_SIGNUP = 'POST_USER_SIGNUP';
export const POST_USER_SIGNUP_SUCCESS = 'POST_USER_SIGNUP_SUCCESS';
export const POST_USER_SIGNUP_FAILED = 'POST_USER_SIGNUP_FAILED';

export const POST_USER_SIGNUP_VERIFY = 'POST_USER_SIGNUP_VERIFY';
export const POST_USER_SIGNUP_VERIFY_SUCCESS = 'POST_USER_SIGNUP_VERIFY_SUCCESS';
export const POST_USER_SIGNUP_VERIFY_FAILED = 'POST_USER_SIGNUP_VERIFY_FAILED';


export const POST_USER_LOGIN_VERIFY = 'POST_USER_LOGIN_VERIFY';
export const POST_USER_LOGIN_VERIFY_SUCCESS = 'POST_USER_LOGIN_VERIFY_SUCCESS';
export const POST_USER_LOGIN_VERIFY_FAILED = 'POST_USER_LOGIN_VERIFY_FAILED';

export const HOTEL_SEARCH = 'HOTEL_SEARCH';
export const HOTEL_SEARCH_SUCCESS = 'HOTEL_SEARCH_SUCCESS';
export const HOTEL_SEARCH_FAILED = 'HOTEL_SEARCH_FAILED';